[web]
  host = "localhost"
  # if running inside docker container/VM
  # host = "0.0.0.0"
  port = 8910
  apiProxyPath = "/.netlify/functions"
[api]
  host = "localhost"
  # if running inside docker container/VM
  # host = "0.0.0.0"
  port = 8911
[browser]
  open = true